### ISSUE TITLE
book hotel: no link to hilton booking page

### ISSUE THREAD

**Issue by binary1230** [magfest/website-issues#15]
we have this URL somewhere, will dig it up

**Comment by shirgoldbird** [comment]
Updated the site. For reference, the URL is https://resweb.passkey.com/Resweb.do?mode=welcome_ei_new&eventID=15108970

**Comment by binary1230** [comment]
good stuff, could you change that to be like:

```
<a href="theURL">The Hilton Alexandria Mark Center</a>
```

**Comment by cybersenshi** [comment]
Messaged Sheva on Slack similarly. @binary1230
