### ISSUE TITLE
book hotel: make link more obvious

### ISSUE THREAD

**Issue by binary1230** [magfest/website-issues#6]
_From @binary1230 on June 3, 2016 12:34_

text could go something like:

_Unfortunately, we didn't budget to have enough human-sized cages onsite. Most Festival-Goers will need to make arrangements at a local sleeping facility. If you are a Festival-Goer that would rather not stray too far from the pack, we have negotiated pricing with a certain sleeping facility that is most definitely NOT a Test Chamber.

Book your room: Hilton Alexandria Mark Center - use this link to get the MagLabs discount_

_Copied from original issue: magfest/webhooktheme#13_

**Comment by binary1230** [comment]
Also: we don't actually have the hotel booking link up there now, insert it

**Comment by shirgoldbird** [comment]
Fixed.
