### ISSUE TITLE
labs: sidebar: 'get there' link is not working

### ISSUE THREAD

**Issue by binary1230** [magfest/website-issues#7]
_From @binary1230 on June 3, 2016 12:35_

the template is missing a closing curly brace, and rendering like this:

```
<a href="{{ url('maglabstestchambers') }">
                    Get There
                </a>
```

_Copied from original issue: magfest/webhooktheme#14_

**Comment by daredoes** [comment]
Fixed, and pulled, just needs to be deployed. Can be closed.

**Comment by cybersenshi** [comment]
Not fixed from my vantage. Page didn't even exist. Fixed in latest push. @migetman9

**Comment by cybersenshi** [comment]
Also MAGLabs: Location now needs text.
